image: maven:3-jdk-11

stages:
  - before_script
  - test
  - build
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   
test:
  stage: test
  script: mvn test

build:
  stage: build
  script: mvn install -B

deploy_staging:
  stage: deploy
  script:
  - ssh root@h167.99.254.202 "cd var/www/ && git pull && exit"
  environment:
    name: prod
    url: https://staging.example.com
  only:
    - master
