image: maven:3-jdk-11

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: mvn test

build:
  stage: build
  script: mvn install -B

deploy_staging:
  stage: deploy
  script: java -jar /target/choreos-server-1.0-runner.jar &

  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master
