image: maven:3-jdk-11

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: mvn test

build:
  stage: build
  script: mvn install -B

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master
